// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfxQgHKsaJvTjIC3WiboPfRZXAFrGNys',
    appId: '1:987101233049:web:f9f465fa47bcaa8e749d08',
    messagingSenderId: '987101233049',
    projectId: 'sign-36f54',
    authDomain: 'sign-36f54.firebaseapp.com',
    storageBucket: 'sign-36f54.firebasestorage.app',
    measurementId: 'G-5MW7ZPWPSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAORRwoiaDkBCwUEc5MfumouiUDUUpL0og',
    appId: '1:987101233049:android:faec8dd57baaf17b749d08',
    messagingSenderId: '987101233049',
    projectId: 'sign-36f54',
    storageBucket: 'sign-36f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCteFNaYIuhZCAReoMN4ALvv3jg_uWfaws',
    appId: '1:987101233049:ios:1eeaece391e19a23749d08',
    messagingSenderId: '987101233049',
    projectId: 'sign-36f54',
    storageBucket: 'sign-36f54.firebasestorage.app',
    androidClientId: '987101233049-ek4j0pbirlqb8la30okgpf3t019licah.apps.googleusercontent.com',
    iosClientId: '987101233049-19psivso8evr3vtbova2gibe4jqodsv6.apps.googleusercontent.com',
    iosBundleId: 'com.toddo.toddo',
  );

}